name: generate-summary
on: [push]

jobs:
  generate-and-fix-summary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Summary
        run: npm run generate-summary
      - name: Fix Summary
        run: npm run fix-summary
      - uses: fregante/setup-git-user@v1
      - name: Commit Summary Changes
        run: |
          git add .
          git commit -m "Update Summary"
          git push
